Test the pg_patch in build.yml (#2)
* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,15 +6,30 @@ on:
   pull_request:
     branches: [ "main" ]
 
-jobs:
-  build:
+env:
+  MDB_LOCALES_DEB_CACHE_KEY: 'mdb-locales-deb'
+  MDB_LOCALES_DEB_NAME: 'mdb-locales_0.0.1-1_amd64.deb'
+  LIBMDBLOCALES_DEB_NAME: 'libmdblocales1_0.0.1-1_amd64.deb'
+  LIBMDBLOCALES_DEV_DEB_NAME: 'libmdblocales-dev_0.0.1-1_amd64.deb'
 
-    runs-on: ubuntu-latest
+jobs:
+  build_mdb_locales:
+
+    runs-on: ubuntu-22.04
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         path: ./src
+    - name: Cache resulting deb packages
+      id: cache-mdb-locales
+      uses: actions/cache@v4
+      with:
+        path: |
+          ${{ env.MDB_LOCALES_DEB_NAME }}
+          ${{ env.LIBMDBLOCALES_DEB_NAME }}
+          ${{ env.LIBMDBLOCALES_DEV_DEB_NAME }}
+        key: ${{ env.MDB_LOCALES_DEB_CACHE_KEY }}
     - name: Install build deps
       run: |
         sudo apt update
@@ -28,5 +43,52 @@ jobs:
         path: |
           ./mdb-locales*
           ./libmdblocales*
+
+  patch_and_build_postgresql:
+    runs-on: ubuntu-22.04
+    needs: [ build_mdb_locales ]
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        path: ./src
+    - uses: actions/checkout@v4
+      with:
+        repository: postgres/postgres
+        path: ./postgres-src
+        ref: 'refs/tags/REL_16_0'
+    - name: Load mdb-locales packages
+      id: cache-mdb-locales
+      uses: actions/cache@v4
+      with:
+        path: |
+          ${{ env.MDB_LOCALES_DEB_NAME }}
+          ${{ env.LIBMDBLOCALES_DEB_NAME }}
+          ${{ env.LIBMDBLOCALES_DEV_DEB_NAME }}
+        key: ${{ env.MDB_LOCALES_DEB_CACHE_KEY }}
+    - name: Fail if no cached packages
+      if: steps.cache-mdb-locales.outputs.cache-hit != 'true'
+      run: |
+        echo "Failed to fetch cached docker images. Will now exit..."
+        exit 1
     - name: Install generated deb packages
       run: sudo dpkg -i *.deb
+    - name: Install PostgreSQL build deps
+      run: sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config
+    - name: Apply patch and install PostgreSQL
+      run: |
+        cd postgres-src
+        git apply ../src/pg_patch/0001-Implement-mdb-locales.patch
+        ./configure --enable-cassert --enable-debug
+        make -s
+        sudo make install
+        echo "/usr/local/pgsql/bin" >> $GITHUB_PATH 
+    - name: Init demo cluster
+      run: |
+        mkdir -p pg_data_dir
+        initdb -D pg_data_dir
+        pg_ctl -D pg_data_dir -l logfile start
+        createdb -p 5432 locales-test
+        psql -p 5432 locales-test -c "select COUNT(*)>0 from pg_collation where collprovider='c' and collname not in ('C', 'POSIX', 'ucs_basic', 'C.UTF-8') and collversion != '2.27';" | grep f
+        psql -p 5432 locales-test -c "SELECT '1-1' < '11' COLLATE \"en_US.utf8\"" | grep f
+
+
